#!/bin/bash

# Complete Brand Migration: Evolution API → ChatFlow
# Update all project files to new brand

echo "🚀 Complete Brand Migration: Evolution API → ChatFlow"
echo "=================================================="

echo ""
echo "📋 Migration Summary:"
echo "===================="

echo ""
echo "✅ Frontend Updates:"
echo "- Browser title: ChatFlow - Business Messaging Platform"
echo "- Project name: chatflow-frontend"
echo "- Login page: Welcome to ChatFlow Dashboard"
echo "- Admin email: admin@chatflow.com"
echo "- Copyright: © ChatFlow"

echo ""
echo "✅ Docker Compose Updates:"
echo "- Container names: evolution-* → chatflow-*"
echo "- Database names: evolution_* → chatflow_*"
echo "- Environment variables: EVOLUTION_* → CHATFLOW_*"
echo "- Network names: evolution-network → chatflow-network"
echo "- Volume names: evolution_data_* → chatflow_data_*"
echo "- Server URLs: evolution-api.beeasy.id → chatflow.beeasy.id"

echo ""
echo "🔄 Next Steps for Complete Migration:"
echo "=================================="

echo ""
echo "1️⃣ Backend Updates:"
echo "   - Update backend package.json"
echo "   - Update backend environment variables"
echo "   - Update API documentation"
echo "   - Update JWT issuer/audience"

echo ""
echo "2️⃣ Environment Files:"
echo "   - Update .env files"
echo "   - Update nginx configuration"
echo "   - Update SSL certificates"
echo "   - Update domain DNS records"

echo ""
echo "3️⃣ Documentation:"
echo "   - Update README.md"
echo "   - Update API documentation"
echo "   - Update deployment guides"
echo "   - Update test scripts"

echo ""
echo "4️⃣ Deployment:"
echo "   - Test Docker Compose configuration"
echo "   - Deploy with new branding"
echo "   - Update CI/CD pipelines"
echo "   - Update monitoring tools"

echo ""
echo "5️⃣ Marketing:"
echo "   - Update website content"
echo "   - Update social media profiles"
echo "   - Update email templates"
echo "   - Update marketing materials"

echo ""
echo "🎯 Migration Commands Ready:"
echo "=========================="
echo ""
echo "Frontend: ✅ Complete"
echo "Docker:   ✅ Complete"
echo "Backend:  ⏳ Pending"
echo "Docs:     ⏳ Pending"
echo "Deploy:   ⏳ Pending"

echo ""
echo "📁 Migration Tools Created:"
echo "========================"
echo "✅ update-frontend-brand.sh - Frontend branding"
echo "✅ update-docker-brand.sh - Docker configuration"
echo "✅ migrate-brand.sh - Complete migration (when ready)"
echo "✅ docker-compose.yml.backup - Original backup"

echo ""
echo "🚀 ChatFlow Migration Progress: 40% Complete"
echo "========================================"
echo "✅ Frontend: Done"
echo "✅ Docker: Done"
echo "⏳ Backend: Pending"
echo "⏳ Documentation: Pending"
echo "⏳ Deployment: Pending"

echo ""
echo "🎯 Ready for Next Phase!"
echo "======================"
echo "Run backend updates when ready to continue migration!"
