#!/bin/bash

# Frontend ChatFlow Test
# Comprehensive frontend testing after brand migration

echo "🧪 Frontend ChatFlow Test"
echo "=========================="

# Check if frontend is running
echo "🔍 Checking frontend server..."
if curl -s http://localhost:3000 > /dev/null 2>&1; then
    echo "✅ Frontend server running on port 3000"
else
    echo "❌ Frontend server not running"
    echo "Starting frontend server..."
    cd frontend && npm start &
    sleep 10
fi

echo ""
echo "🌐 Opening Frontend Application..."
echo "================================"

# Open browser with frontend
if command -v open > /dev/null 2>&1; then
    # macOS
    open http://localhost:3000
elif command -v xdg-open > /dev/null 2>&1; then
    # Linux
    xdg-open http://localhost:3000
elif command -v start > /dev/null 2>&1; then
    # Windows
    start http://localhost:3000
else
    echo "Please open browser manually: http://localhost:3000"
fi

echo ""
echo "📋 Frontend ChatFlow Test Checklist:"
echo "=================================="
echo ""
echo "🎨 1. Branding & UI Test:"
echo "   ✓ Browser title shows 'ChatFlow - Business Messaging Platform'"
echo "   ✓ Login page shows 'Welcome to ChatFlow Dashboard'"
echo "   ✓ Copyright shows '© ChatFlow'"
echo "   ✓ Admin email shows 'admin@chatflow.com'"
echo "   ✓ All UI elements use ChatFlow branding"
echo ""
echo "🔐 2. Authentication Test:"
echo "   ✓ Login form loads correctly"
echo "   ✓ Validation messages work"
echo "   ✓ Login with: admin@example.com / Admin123"
echo "   ✓ Successful login redirects to dashboard"
echo "   ✓ Failed login shows error messages"
echo "   ✓ Logout functionality works"
echo ""
echo "📱 3. Navigation Test:"
echo "   ✓ Sidebar menu items display correctly"
echo "   ✓ Navigation to Dashboard works"
echo "   ✓ Navigation to Phones works"
echo "   ✓ Navigation to Messages works"
echo "   ✓ Navigation to Templates works"
echo "   ✓ Navigation to API Keys works"
echo "   ✓ Navigation to Scheduled Messages works"
echo "   ✓ Navigation to External WhatsApp works"
echo "   ✓ Navigation to Users works"
echo "   ✓ Navigation to Settings works"
echo ""
echo "🎯 4. Dashboard Test:"
echo "   ✓ User info displays correctly"
echo "   ✓ Statistics cards show data"
echo "   ✓ Charts render properly"
echo "   ✓ Recent activities display"
echo "   ✓ Quick actions work"
echo ""
echo "📱 5. Phone Management Test:"
echo "   ✓ Phone list displays"
echo "   ✓ Add Phone dialog opens"
echo "   ✓ Phone form validation works"
echo "   ✓ QR code generation works"
echo "   ✓ Phone status updates"
echo "   ✓ Phone deletion works"
echo "   ✓ Real-time status updates"
echo ""
echo "💬 6. Messages Test:"
echo "   ✓ Message list displays"
echo "   ✓ Send Message dialog opens"
echo "   ✓ Phone selection works"
echo "   ✓ Recipient input works"
echo "   ✓ Message composition works"
echo "   ✓ Message sending works"
echo "   ✓ Message history displays"
echo "   ✓ Search/filter works"
echo ""
echo "📝 7. Templates Test:"
echo "   ✓ Template list displays"
echo "   ✓ Create Template dialog opens"
echo "   ✓ Template form validation works"
echo "   ✓ Template creation works"
echo "   ✓ Template editing works"
echo "   ✓ Template deletion works"
echo "   ✓ Variable placeholders work"
echo ""
echo "🔑 8. API Keys Test:"
echo "   ✓ API key list displays"
echo "   ✓ Create API Key dialog opens"
echo "   ✓ API key generation works"
echo "   ✓ Permission settings work"
echo "   ✓ API key regeneration works"
echo "   ✓ API key deletion works"
echo ""
echo "⏰ 9. Scheduled Messages Test:"
echo "   ✓ Scheduled list displays"
echo "   ✓ Schedule Message dialog opens"
echo "   ✓ Time picker works"
echo "   ✓ Message scheduling works"
echo "   ✓ Schedule editing works"
echo "   ✓ Schedule deletion works"
echo "   ✓ Status tracking works"
echo ""
echo "🔄 10. Session Handling Test:"
echo "   ✓ Login maintains session after refresh"
echo "   ✓ Loading spinner shows during session check"
echo "   ✓ Logout clears session"
echo "   ✓ Multiple tabs sync session"
echo "   ✓ Invalid session redirects to login"
echo ""
echo "📱 11. Responsive Design Test:"
echo "   ✓ Desktop layout works correctly"
echo "   ✓ Tablet layout adapts properly"
echo "   ✓ Mobile layout works correctly"
echo "   ✓ Sidebar toggle works on mobile"
echo "   ✓ Touch interactions work"
echo ""
echo "🔍 12. Browser Dev Tools Test:"
echo "   ✓ Console shows no JavaScript errors"
echo "   ✓ Network tab shows successful API calls"
echo "   ✓ Application tab shows correct localStorage"
echo "   ✓ Elements tab renders correctly"
echo "   ✓ No 404 errors for assets"
echo ""
echo "🎯 13. Performance Test:"
echo "   ✓ Page load times are acceptable"
echo "   ✓ Animations are smooth"
echo "   ✓ No memory leaks detected"
echo "   ✓ Responsive images load properly"
echo "   ✓ API responses are fast"
echo ""
echo "🌐 Frontend Test URLs:"
echo "========================"
echo "Main Application: http://localhost:3000"
echo "Login Page:      http://localhost:3000/login"
echo "Dashboard:       http://localhost:3000/dashboard"
echo "Phones:          http://localhost:3000/phones"
echo "Messages:        http://localhost:3000/messages"
echo "Templates:       http://localhost:3000/templates"
echo "API Keys:        http://localhost:3000/api-keys"
echo "Schedules:       http://localhost:3000/schedules"
echo "External WhatsApp: http://localhost:3000/external-whatsapp"
echo "Users:           http://localhost:3000/users"
echo "Settings:         http://localhost:3000/settings"
echo ""
echo "🔧 Test Instructions:"
echo "===================="
echo "1. Open browser at http://localhost:3000"
echo "2. Test all checklist items above"
echo "3. Use browser dev tools (F12) to monitor"
echo "4. Report any issues or errors found"
echo "5. Verify ChatFlow branding throughout"
echo ""
echo "✅ Frontend ChatFlow Test Ready!"
echo "================================"
echo "🌐 Browser opened with: http://localhost:3000"
echo "📋 Follow checklist above for comprehensive testing!"
echo "🔍 Use browser dev tools to monitor issues!"
echo "🎯 Test all ChatFlow functionality thoroughly!"
